### PR TITLE
Full fledged cli

### PR DESCRIPTION
**Pull request by bnvk**
Merging these changes as they really improve the overall!

### CODE REVIEW

**Comment by simonv3** [comment]
Have you published this to NPM?

**Comment by bnvk** [comment]
@simonv3 I had not updated that in awhile, thanks for reminding me! I just nuked the branch, so everything is on master and current with all my local changes. I'm pretty sure `setup` does not properly work given the current needs for projects in the config, but that should be trivial to add!

**Comment by simonv3** [comment]
I used to have it setup that my commandline tool pointed to my local dev install, but I think I overwrote that somehow so I want to see whether a clean install of it fixes it.

**Comment by bnvk** [comment]
Yah, so you don't want to the use `npm install -g` option in this case. You want to clone it to wherever you keep code your working on, then `cd path/to/Conjuror` into that directory, then do `sudo npm link` which then makes it accessible as a global command, but still be able to do devlopment!

**Comment by simonv3** [comment]
aha!

**Pull request merged**
